#!/usr/bin/env php

<?php

require __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Application;
use Skeleton\Command\SkeletonCommand as SkeletonCommand;

$app = new Application;
$skeleton = new SkeletonCommand;


$app->add($skeleton);

$app->run();